# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d4e4986b84de493c15b695950516863caa7d68dba9bc4c427e66cdbc5a3a9074bbe5bae12c4ef2b394e5d25629dc3f7cd841c4525b3d3388842873ec3376f79f

test:
  secret_key_base: 2bef3bcb5f925af1775b9b45815b86134fe1afc2a0c6b54a949632e64d99259cbbabc9dc91a3260962c4965c63edfe0e4cd18f6aeea0a2c46c087fbe7f39b4fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
